services:
#  db:
#    image: postgres:12
#    environment:
#      POSTGRES_MULTIPLE_DATABASES: northwind,northwind_target
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: thewindisblowing
#    volumes:
#      - ./dbdata:/var/lib/postgresql/data
#      - ./data/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
#      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
#    ports:
#      - 5432:5432

  meltano:
    image: meltano/meltano:v3.5.4-python3.10
    volumes:
      - ./meltano:/project
      - ./data:/data
    ports:
      - 5000:5000
#    depends_on:
#      - db
    working_dir: /project
    entrypoint: >
      /bin/bash -c "
      if [ ! -f meltano.yml ]; then
        meltano init my_project --no_usage_stats &&
        mv my_project/* ./ &&
        rm -r my_project;
      fi &&
      tail -f /dev/null"

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow-webserver
    ports:
      - 8080:8080
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-db
    entrypoint: >
      /bin/bash -c "
      airflow db upgrade &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-webserver
      - airflow-db
    command: airflow scheduler

  airflow-db:
    image: postgres:12
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./airflow/db:/var/lib/postgresql/data
    ports:
      - 5433:5432